### ISSUE TITLE
Highlight text on 2 lines 

### ISSUE THREAD

**Issue by mcrassin** [yavorskiy/angular-input-highlight#1]
Hi man, 

First, i want to thank you for this directive, it helped me a lot. It's simple, and exactly what I was looking for. 

I just wanted to submit an issue I've met and work on using this directive. Let me explain: If you try to highlight several words, on 2 lines, the directive will try to highlight the whole expression at once and will fail. 
Here is a simple plnkr to show you (in case it's not clear): 
http://plnkr.co/edit/oqzTzJnuhSNxqFkoCuuE?p=preview

I've been working on some improvement, to fix this. Are you interested ? 

bye

**Comment by syavorsky** [comment]
@mcrassin sorry somehow I overlooked your request. I can reproduce the issue and will try to deal with it unless you have a pull request already.

**Comment by syavorsky** [comment]
@mcrassin ok, got a quick fix will check across different browsers and publish

**Comment by syavorsky** [comment]
@mcrassin would appreciate if you pull the branch and check if it solves the issue

**Comment by syavorsky** [comment]
@mcrassin published `0.1.2`

**Comment by mcrassin** [comment]
@yavorskiy hey, thanks. I'll try it and let you know.
